server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/v370r/getmyuri-config
          default-label: main
          clone-on-start: true
          search-paths:
            - config
  application:
    name: config-server
