server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/v370r/getmyuri-config
          default-label: main
          clone-on-start: true
          search-paths:
            - config
    loadbalancer:
      retry:
        enabled: true  # Optional: allows retrying discovery-based requests if using WebClient or Feign

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
